// <auto-generated />
using System;
using API.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Domain.Model.Entities.ServidorProxy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_servidor");

                    b.Property<string>("Anonimato")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("anonimato");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("codigo_pais");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pais");

                    b.Property<bool?>("Https")
                        .HasColumnType("bit")
                        .HasColumnName("https");

                    b.Property<string>("Ip")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ip");

                    b.Property<double?>("Latencia")
                        .HasColumnType("float")
                        .HasColumnName("latencia");

                    b.Property<int?>("Porta")
                        .HasColumnType("int")
                        .HasColumnName("porta");

                    b.Property<string>("Protocolo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("protocolo");

                    b.Property<double?>("UltimaVerificacao")
                        .HasColumnType("float")
                        .HasColumnName("ultima_verificacao");

                    b.HasKey("Id");

                    b.ToTable("servidores_proxy", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
